firstNum = int(input("Первое число"))
secondNum = int(input("Второе число"))
thirdNum = int(input("Третье число"))
fourthNum = int(input("Четвертое число"))
result = (firstNum + secondNum) / (thirdNum + fourthNum)
print("Ответ: %.2f " % result)
